version: '3.8'

services:
  responsive-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    container_name: trustml-responsive-tests
    volumes:
      - ./frontend/src:/app/frontend/src:ro
      - ./frontend/public:/app/frontend/public:ro
      - ./test-results:/app/frontend/test-results
      - ./docs:/app/docs:ro
      - ./scripts:/app/scripts:ro
    environment:
      - NODE_ENV=test
      - CI=true
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    ports:
      - "3000:3000"
    command: bash -c "npm run test:coverage -- --testPathPattern=responsiveDesignUtils --watchAll=false"
    networks:
      - test-network

  e2e-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    container_name: trustml-e2e-tests
    volumes:
      - ./frontend/src:/app/frontend/src:ro
      - ./frontend/public:/app/frontend/public:ro
      - ./test-results:/app/frontend/test-results
      - ./docs:/app/docs:ro
      - ./scripts:/app/scripts:ro
    environment:
      - NODE_ENV=test
      - CI=true
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    ports:
      - "3001:3000"
    command: bash -c "npm start & sleep 15 && npm run test:e2e -- responsiveDesignTests.test.js --reporter=json --output-dir=test-results"
    networks:
      - test-network

  performance-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    container_name: trustml-performance-tests
    volumes:
      - ./frontend/src:/app/frontend/src:ro
      - ./test-results:/app/frontend/test-results
    environment:
      - NODE_ENV=test
      - CI=true
    command: npm run test:performance -- --testPathPattern=responsivePerformance --runInBand --json --outputFile=test-results/performance-results.json
    networks:
      - test-network

  test-runner:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    container_name: trustml-test-runner
    volumes:
      - ./frontend:/app/frontend
      - ./test-results:/app/test-results
      - ./docs:/app/docs:ro
      - ./scripts:/app/scripts:ro
    environment:
      - NODE_ENV=test
      - CI=true
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    ports:
      - "3002:3000"
    command: bash /app/scripts/run-responsive-tests.sh
    depends_on:
      - responsive-tests
      - performance-tests
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  test-results:
    driver: local